---
version: '3'
services:
  binance_delist:
    build:
      context: .
      dockerfile: "./Dockerfile"
    container_name: binance_delist
    image: binance_delist:latest
    restart: unless-stopped
    volumes:
      # Map your local config to a new file in the container and use in instances.json
      - /opt/appdata/freqtrade/user_data_infinity/config.json:/app/configs/usdt.json
      - /opt/appdata/freqtrade/user_data_infinity_busd/config.json:/app/configs/busd.json
      # Map the instances.json file with your configuration
      - /opt/appdata/freqtrade/delister-instances.json:/app/instances.json"
    networks: 
      freqtrade:
        ipv4_address: 172.31.0.101

networks:
  freqtrade:
    external: true

# Define this network in freqtrade's docker-compose and use it on your freqtrade containers
# networks:
#   freqtrade:
#     name: freqtrade
#     driver: bridge
#     ipam:
#      config:
#        - subnet: 172.31.0.0/16
#          gateway: 172.31.0.1